# Força o uso de uma versão moderna do Node.js
[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.build]
cmds = ["npm install", "npm run build"]

# Define explicitamente o comando de inicialização como Node.js
[start]
cmd = "npm run preview"
